services:
  nginx:
    image: nginx:alpine
    ports:
      - "10099:80"
    volumes:
      - ./:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - 1cms

  php:
    image: 1cms/1cms:fpm74
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    command: sh -c "chown -R www-data:www-data /var/www/html && chmod -R 755 /var/www/html && php-fpm"
    networks:
      - 1cms

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1cms
      MYSQL_DATABASE: 1cms
    networks:
      - 1cms
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./database/mysql:/var/lib/mysql

networks:
  1cms: